### PR TITLE
fix build with qt 5.5

### PR DESCRIPTION
**Pull request by rezso**
(lxqtnotification.h:43:5: error: 'Q_OBJECT' does not name a type)

### CODE REVIEW

**Comment by paulolieuthier** [comment]
Merged in 7303ea207de0771d6f450a31ec4a1ce69202869b. Thanks.
